version: "2"
run:
  modules-download-mode: readonly
  tests: false
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - revive
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    revive:
      rules:
        - name: exported
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1*
        - -QF1*
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
