// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Szymon Wilczek
// LOTA Attestation CA - ROCA (CVE-2017-15361) fingerprint detection
//
// Infineon RSALib generated RSA primes of the form k*M + (65537^a mod M)
// with M a primorial, so every affected modulus N = p*q satisfies
// N == 65537^c (mod M).
//
// Coppersmith-based ROCA attack recovers the private key from such a
// modulus alone, which makes credential activation forgeable in software:
// the attacker factors the EK, unwraps MakeCredential without a TPM, and
// walks away with a valid AIK certificate.
//
// Affected EKs are rejected outright - a manufacturer CRL may lag or be
// unconfigured, but the fingerprint is intrinsic to the key.
//
// Detection ("The Return of Coppersmith's Attack"):
// for each small prime p below, test whether N mod p lies in the
// multiplicative subgroup generated by 65537 mod p. The subgroups are
// small relative to p-1; an RSALib modulus passes by construction
// because every prime below divides the primorial M used at every
// affected key size.

package ca

import "math/big"

// rocaPrimes are the 17 discriminating primes from the ROCA paper's
// fingerprint test.
// All lie below 167, so they divide the RSALib primorial M at every
// affected key size (512-4096 bit).
var rocaPrimes = [...]int64{
	11, 13, 17, 19, 37, 53, 61, 71, 73,
	79, 97, 103, 107, 109, 127, 151, 157,
}

// rocaPrints[i] is a bitmask over residues mod rocaPrimes[i]:
// bit r is set iff r is in the subgroup generated by 65537.
// Computed from the definition at startup instead of being
// embedded as opaque constants so the table cannot silently
// drift from the primes list.
var rocaPrints [len(rocaPrimes)]*big.Int

func init() {
	for i, p := range rocaPrimes {
		mask := new(big.Int)
		for r := int64(1); ; {
			mask.SetBit(mask, int(r), 1)
			r = r * 65537 % p
			if r == 1 {
				break
			}
		}
		rocaPrints[i] = mask
	}
}

// IsROCAWeak reports whether an RSA modulus carries the ROCA
// fingerprint, i.e. its prime factors were generated by the affected
// Infineon RSALib and the private key is recoverable from N alone.
func IsROCAWeak(n *big.Int) bool {
	if n == nil || n.Sign() <= 0 {
		return false
	}
	rem := new(big.Int)
	for i, p := range rocaPrimes {
		r := rem.Mod(n, big.NewInt(p)).Int64()
		if rocaPrints[i].Bit(int(r)) == 0 {
			return false
		}
	}
	return true
}
