// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Szymon Wilczek
// LOTA Load Generator - Rig policy generation
//
// Emits the PCR policy matching the fleet's shared measurement profile,
// so the verifier under test runs its production configuration:
// raw PCR 0/1/7 pins (satisfies the first-attestation boot-enrollment gate
// without TOFU opt-outs), pinned kernel and agent hashes,
// and the enforcement/module-sig requirements the synthetic reports advertise.
//
// PCR 14 is deliberately never pinned:
// it is the boot-commitment register the verifier validates by derivation.

package synth

import (
	"encoding/hex"
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/szymonwilczek/lota/verifier/verify"
)

// PolicyName is the policy the rig ships to the verifier under test
const PolicyName = "lota-loadgen"

// Policy returns the fleet's PCR policy
func (f *Fleet) Policy() *verify.PCRPolicy {
	return &verify.PCRPolicy{
		Name:        PolicyName,
		Description: "synthetic load-test fleet profile (generated by lota-loadgen)",
		PCRs: map[int]string{
			0: hex.EncodeToString(f.PCRs[0][:]),
			1: hex.EncodeToString(f.PCRs[1][:]),
			7: hex.EncodeToString(f.PCRs[7][:]),
		},
		KernelHashes:     []string{hex.EncodeToString(f.KernelHash[:])},
		AgentHashes:      []string{hex.EncodeToString(f.AgentHash[:])},
		RequireEnforce:   true,
		RequireModuleSig: true,
	}
}

// PolicyYAML renders Policy for the verifier's --policy flag
func (f *Fleet) PolicyYAML() ([]byte, error) {
	out, err := yaml.Marshal(f.Policy())
	if err != nil {
		return nil, fmt.Errorf("marshal rig policy: %w", err)
	}
	return out, nil
}
