# SPDX-License-Identifier: MIT
{{- if and .Values.postgres.dsn (not .Values.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lota-verifier.pgSecretName" . }}
  labels:
    {{- include "lota-verifier.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.dsnKey }}: {{ .Values.postgres.dsn | quote }}
{{- end }}
