#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Materialize a pinned EK manufacturer root bundle from a sources file.
#
# For each vendor line the tool fetches the root, recomputes the SHA-256
# over its DER, and refuses to write it unless the fingerprint matches the
# pin recorded in the sources file. The result is a directory the
# attestation CA consumes with -ek-root-bundle: an ek-roots.manifest plus
# one PEM per root, with the manifest pinning every file.
#
# Usage:
#   scripts/lota-ek-roots-update.sh <sources-file> <output-dir>
#
# See configs/ek-roots/README.rst for the provisioning flow.

set -euo pipefail

MANIFEST_NAME="ek-roots.manifest"
PLACEHOLDER="REPLACE_ME"

die() {
	echo "lota-ek-roots-update: $*" >&2
	exit 1
}

[ $# -eq 2 ] || die "usage: $0 <sources-file> <output-dir>"
SOURCES="$1"
OUTDIR="$2"

[ -r "$SOURCES" ] || die "cannot read sources file: $SOURCES"
command -v openssl >/dev/null 2>&1 || die "openssl not found"
command -v curl >/dev/null 2>&1 || die "curl not found"
command -v sha256sum >/dev/null 2>&1 || die "sha256sum not found"

mkdir -p "$OUTDIR"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/lota-ek-roots.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

MANIFEST="$WORK/$MANIFEST_NAME"
{
	echo "# LOTA EK manufacturer root bundle manifest."
	echo "# Generated by lota-ek-roots-update.sh -- do not hand-edit; edit the"
	echo "# sources file and regenerate so the pins stay verified."
	echo "#"
	echo "#   <sha256>  <filename>  <vendor label>"
} >"$MANIFEST"

# to_pem reads a certificate in DER or PEM and writes it back as PEM.
to_pem() {
	local in="$1" out="$2"
	if openssl x509 -inform DER -in "$in" -outform PEM -out "$out" 2>/dev/null; then
		return 0
	fi
	openssl x509 -inform PEM -in "$in" -outform PEM -out "$out" 2>/dev/null
}

# der_sha256 prints the lowercase hex SHA-256 over a PEM certificate's DER.
der_sha256() {
	openssl x509 -inform PEM -in "$1" -outform DER 2>/dev/null |
		sha256sum | cut -d' ' -f1
}

count=0
while IFS= read -r line || [ -n "$line" ]; do
	case "$line" in
	'' | \#*) continue ;;
	esac

	read -r pin filename url label <<<"$line"
	[ -n "$pin" ] && [ -n "$filename" ] && [ -n "$url" ] ||
		die "malformed sources line: $line"

	[ "$pin" = "$PLACEHOLDER" ] &&
		die "unverified pin for $filename: replace $PLACEHOLDER with the vendor's published SHA-256"

	pin="$(printf '%s' "$pin" | tr 'A-F' 'a-f')"
	[[ "$pin" =~ ^[0-9a-f]{64}$ ]] || die "pin for $filename is not a 64-hex SHA-256"
	[ "$filename" = "$(basename -- "$filename")" ] ||
		die "filename must be a bare name: $filename"

	raw="$WORK/raw"
	curl -fsSL --proto '=https' --tlsv1.2 -o "$raw" "$url" ||
		die "failed to fetch $label from $url"

	pem="$WORK/$filename"
	to_pem "$raw" "$pem" || die "downloaded $label is not a certificate"

	got="$(der_sha256 "$pem")"
	[ "$got" = "$pin" ] ||
		die "fingerprint mismatch for $label: pinned $pin, fetched $got"

	echo "$pin  $filename  $label" >>"$MANIFEST"
	echo "verified $label ($pin)"
	count=$((count + 1))
done <"$SOURCES"

[ "$count" -gt 0 ] || die "no vendor roots in $SOURCES"

# stage the whole bundle, then move every file into
# place so a half-written bundle never reaches the CA
install -m 0644 "$MANIFEST" "$OUTDIR/$MANIFEST_NAME"
for pem in "$WORK"/*.pem; do
	[ -e "$pem" ] || continue
	install -m 0644 "$pem" "$OUTDIR/$(basename -- "$pem")"
done

echo "wrote $count pinned root(s) to $OUTDIR"
